name: Build and Test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: wget https://github.com/official-stockfish/Stockfish/releases/latest/download/stockfish-ubuntu-x86-64-avx2.tar.xz
      - run: tar -xJf stockfish-ubuntu-x86-64-avx2.tar.xz
      - run: chmod +x stockfish-ubuntu-x86-64-avx2
      - run: ln -s stockfish-ubuntu-x86-64-avx2 stockfish
      - run: go build -v ./...
      - run: go test -v -bench=. ./...
